management:
  endpoints:
    web:
      exposure:
        include: health, metrics

server:
  port: 8081

  cors:
    allowed-origins: "*"
    allowed-headers: "*"
    allowed-methods: GET, POST, PUT, DELETE, OPTIONS
    max-age: 1800
    exposed-headers: "Content-Disposition"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/salon_booking
    username: postgres
    password: KhongCoPass1986@
  liquibase:
    change-log: classpath:/db/changelog/db.xml
  jpa:
    properties:
      hibernate:
        format_sql: true

jwt:
  validity-in-ms: 86_400_000 # 24h
  secret-key: daylachiakhoabimatcuatoi

app:
  title: "@project.description@"
  version: "@project.version@"
  gift-code-length: 8

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        orm:
          jdbc:
            bind: TRACE
